// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgxyE0m5Vl8G1BJgyAjATdKe2HXm-tW8',
    appId: '1:789340116026:web:4d50c04e99a1af35881103',
    messagingSenderId: '789340116026',
    projectId: 'diarify-cd6e0',
    authDomain: 'diarify-cd6e0.firebaseapp.com',
    storageBucket: 'diarify-cd6e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCpxhJ0lD_oHxcPgdlFmo-_GYcjKzHP4',
    appId: '1:789340116026:android:9adb81688e979d4d881103',
    messagingSenderId: '789340116026',
    projectId: 'diarify-cd6e0',
    storageBucket: 'diarify-cd6e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEIZTo1ynDNqkLASOKaRA8kbTvmHod7TY',
    appId: '1:789340116026:ios:32ff97c0122796c9881103',
    messagingSenderId: '789340116026',
    projectId: 'diarify-cd6e0',
    storageBucket: 'diarify-cd6e0.appspot.com',
    androidClientId: '789340116026-ihajqetp6rhkiksr2441f91njl23s4iv.apps.googleusercontent.com',
    iosClientId: '789340116026-pajm0vflsligul9o52a7bk35b1s2jj7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.diarifyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEIZTo1ynDNqkLASOKaRA8kbTvmHod7TY',
    appId: '1:789340116026:ios:693f491bff416f44881103',
    messagingSenderId: '789340116026',
    projectId: 'diarify-cd6e0',
    storageBucket: 'diarify-cd6e0.appspot.com',
    androidClientId: '789340116026-ihajqetp6rhkiksr2441f91njl23s4iv.apps.googleusercontent.com',
    iosClientId: '789340116026-6s0p5plnjebiltd2tlibm8m5qlg3oi1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.diarify.RunnerTests',
  );
}
